[NoticeList]
[[NoticeList.List]]
Channel = 1
Content = "Dear commanders,\nWelcome to this battlefield full of crisis. \n\nThe Last Raiders will officially open at 10:00 am PST on November 29th, 2020.\n\nAt that time, there will be a huge number of activities to help commanders go on an expedition.\nPlease check the details in the game or focus on our official FaceBook: The Last Raiders for recent developments.\n\nThank you for your support to \"The Last Raiders\".\nWish you a happy game!\n\nBest Regards from the Last Raiders operation team."

